### ISSUE TITLE
Creator plugins cannot be enabled/disabled 🔀 on demand

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#1931]
### Bug

We have `enabled` property on Settings per creator plugin (at least in Maya), but Avalon doesn't support enabling/disabling or filtering creator plugins on demand. It is misleading to have checkbox to disable/enable creator plugin without having any effect.

#### Proposal

Either add plugin filtering as was done in **pyblish-base**:
https://github.com/pyblish/pyblish-base/blob/aaec8a8265fa4d93e6e19fedc172bf332c771b56/pyblish/plugin.py#L1205-L1244

then filtering can be achieved on each host directly in OpenPype without adding further changes to avalon-core.

[cuID:PYPE-1247]

**Comment by mkolar** [comment]
I believe this has been fixed in the new publisher already, wasn't it @iLLiCiTiT ?

**Comment by iLLiCiTiT** [comment]
Just checked and creators for new creator have `enabled` attribute but is not validated at any point (easy fix).

But I think this issue is more related to settings where we have checkboxes on creators in Maya...
![image](https://user-images.githubusercontent.com/43494761/172562903-a4f4444f-e30b-4d25-9b91-9bb4b8a3ef52.png)

**Comment by iLLiCiTiT** [comment]
Issue is resolved. In Publisher with https://github.com/ynput/OpenPype/pull/4500 andin legacy create tool too (I could find PR fixing it).
