### ISSUE TITLE
OpenPype igniter locations and versions

### ISSUE THREAD

**Issue by iLLiCiTiT** [ynput/OpenPype#2388]
## Description
Class `OpenPypeVersion` in igniter has too much responsibility to do. It should be used to be create object of semantic version for comparing but right now it also cares about path to a specific version which is required in some cases but is optional in initialization. Because the current base (comparing to other versions) is needed we should extract the path logic to different class.

I think we need more than one class. I think we need something  like "OpenPypeLocation" and "OpenPypePackage" (names are not final). OpenPypePackage is representation of one OpenPypeVersion in the OpenPypeLocation. OpenPypeLocation has discovery of available OpenPypePackages and ability to download (and install?) OpenPypePackage.

OpenPypePackage should know if is "build package" inside OpenPype build, "local package" downloaded and extracted zip on workstation or "remote package" which has to be downloaded and extracted to local versions.

Since "remote package" is downloaded and extracted it should be also available as "local package".

If there is OpenPypePackage available on the workstation ("build package" or "local package") then other packages should be skipped as we already have needed version on the workstation.

### Why we might need this
- we can extend abilities how and from where zips are downloaded

[cuID:[OP-2154](https://app.clickup.com/t/1x5c48f)]

**Comment by antirotor** [comment]
I agree.

- **OpenPypeVersion** should only have semver related stuff (comparsion, string conversions, ...)
- **OpenPypeLocation** should be based on URI and utilize schemas to define how to access different locations (file, https, git, ...) and be used as factory class for classes implementing specific locations (*OpenPypeFileLocation*, *OpenPypeGitLocation*, ...)
- **OpenPypePackage** should have then **OpenPypeVerison** and **OpenPypeLocation** as properties. We should probably unify structure of OpenPype packages (versions), because those coming from zips are different then the built one that comes with igniter.
