### ISSUE TITLE
Maya: os.getcwd()

### ISSUE THREAD

**Issue by zhoub** [ynput/OpenPype#2881]
**Describe the bug**
The cwd of Maya application should be set properly.

**To Reproduce**
Launch Maya from Launcher for a new task, open Python script Window, use
```python
import os
print os.getcwd()
```
to inspect the cwd, it would print the `D:\Development\OpenPype-repo\igniter` which is the igniter folder path.

**Expected behavior**
This path should be a path for current asset.

**Desktop (please complete the following information):**
 - OS: Windows
 - Host: Maya

**Additional context**
3.9.0-nightly.9

**Comment by iLLiCiTiT** [comment]
> This path should be a path for current asset.

Can you describe the use case? Because I'm afraid that is irrelevant request to set right cwd to be able use `os.getcwd` to get directory of opened scene.

CWD (Current work directory) is set at the start of Maya process and does not change during it's lifetime. If you would open scene from different folder using `File > Open Scene` the **cwd** would not change.

Also you can open .ma/.mb file using cmd (or Poweshell):
```
> cd C:/Windows
> D:/path/to/your/file.ma
```
The **cwd** would be `C:/Windows` or anything you pass after `cd ...`.
