### ISSUE TITLE
Loader: Published versions menu entries errors and mismatches

### ISSUE THREAD

**Issue by maxpareschi** [ynput/OpenPype#3760]
**Describe the bug**
Published reviews from local or farm can't be played directly in loader (both in app and standalone).
This happens only if the review is published using either "local" or "On farm" (tested on Nuke)
After publishing Loader displays a "Play <repre>" entry for all the representations in addition to the usual "Open in DJV"
If any entry other than "Open in DJV" and "Play (exr)" is selected loader returns a list index out of range error
If version is published using "Use existing frames" the play options do not appear at all.
Also, the menu entries are being constructed based on last publish, so if someone publishes on farm loader gets the options, afterwards if someone publishes a new version with use existing frames the previous play entries disappear.

**To Reproduce**
1. Publish from nuke with either "local" or "On farm" and Review checked
2. open loader (either from tray or in app)
3. select the published asset and right click
4. See error when selecting all play entries other than "Play (exr)"
5. republish a new version with "Use existing frames"
6. open loader, select asset and right click
7. Play entries disappear, only "Open in DJV (exr)" is available

**Expected behavior**
same behaviour for all three publish modes ("Use existing frames, "local", "On farm").
Best if we get the play entries, to see a mov i need to copy file to desktop every time or use the delivery option and navigate there.

**Screenshots**
Version published with either "Local" or "On Farm" 
![repre](https://user-images.githubusercontent.com/19264472/187456327-a6f66eac-96f9-44fa-95e1-ab06299cbf1d.jpg)

Error when selecting any play entry aside from exr
![error](https://user-images.githubusercontent.com/19264472/187456494-b89caa3f-f792-44bd-bccd-cbc5bebd9076.jpg)

Play entries disappears when republishing a new version with "Use Existing Frames"
![Use-External-Frames](https://user-images.githubusercontent.com/19264472/187456574-4d22bcfa-3f49-4ae6-a6c4-bb51f6b7de55.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Host: Tested only in Nuke 12.1, 13.1 and 13.2

[cuID:[OP-3853](https://app.clickup.com/t/2t3wjy8)]

**Comment by m-u-r-p-h-y** [comment]
@maxpareschi what is your OP version?

**Comment by maxpareschi** [comment]
3.14.1, fresh from today

**Comment by BigRoy** [comment]
@maxpareschi Could you try the Open File action as set up in #3762. I assume that should actually work for all the different representations.

---

> republish a new version with "Use existing frames"
> open loader, select asset and right click
> Play entries disappear, only "Open in DJV (exr)" is available

The PR I linked does **NOT** fix this issue. That part of the issue is likely related to the thumbnail and other encodings not getting generated when using the "Use existing frames" option.

My first hunch is that that issue is related to [logic here](https://github.com/pypeclub/OpenPype/blob/137ba908b51acf1a79963e71dc9278ec935f002a/openpype/hosts/nuke/plugins/publish/precollect_instances.py#L87) and potentially the line `family = families_ak.lower()` might need to be also set there. 

However, the code in that file is throwing me off a bit because [it seems to try to get a list using `families_ak = avalon_knob_data.get("families", [])`](https://github.com/pypeclub/OpenPype/blob/137ba908b51acf1a79963e71dc9278ec935f002a/openpype/hosts/nuke/plugins/publish/precollect_instances.py#L52) but does `families_ak.lower()` - however lists don't have a `.lower()` method.

```python
my_list = ["a", "B"]
print(my_list.lower())
# AttributeError: 'list' object has no attribute 'lower' # 
```

**Comment by iLLiCiTiT** [comment]
Was not fully resolved

**Comment by maxpareschi** [comment]
Confirmed that it's only partially resolved. After @BigRoy pr yesterday the menu entries work as intended.
Instead the entries gets removed if the publish was made with "Use Existing Frames", while they reappear afterwards if i publish either "on farm" or "local"

**Comment by BigRoy** [comment]
> However, the code in that file is throwing me off a bit because [it seems to try to get a list using `families_ak = avalon_knob_data.get("families", [])`](https://github.com/pypeclub/OpenPype/blob/137ba908b51acf1a79963e71dc9278ec935f002a/openpype/hosts/nuke/plugins/publish/precollect_instances.py#L52) but does `families_ak.lower()` - however lists don't have a `.lower()` method.

Any chance you could try publishing with that implemented? Not sure if that's the right fix. :)

**Comment by maxpareschi** [comment]
I tried dumping the collected instances and the only difference that i can see here is this:
```
Use existing frames:
    ...
    "families": [
        "review",
        "write"
    ],
    ...
Local:
    ...
    "families": [
        "review",
        "render.local"
    ],
    ...
On Farm
    ...
    "families": [
        "review",
        "render.farm"
    ],
    ...
```

Seems this is not the place...

**Comment by BigRoy** [comment]
@maxpareschi I don't think is the Integrator, no - it might be but I don't think so.

The families you listed does show a potential root to the problem. When using existing frames the `render` family does not get added but things like [ExtractThumbnail](https://github.com/pypeclub/OpenPype/blob/develop/openpype/plugins/publish/extract_thumbnail.py) wouldn't run. Which would explain why e.g. a thumbnail is not published along. I assume the same is true for the Publish plug-ins that produce the H264 movs and dnxhd representations. Likely the [ExtractReview](https://github.com/pypeclub/OpenPype/blob/4160713a62c3f7325fb7e5701d14e0edb92fe892/openpype/plugins/publish/extract_review.py) logic doesn't think it should do anything because it's maybe not matching `render` e.g. [here](https://github.com/pypeclub/OpenPype/blob/4160713a62c3f7325fb7e5701d14e0edb92fe892/openpype/plugins/publish/extract_review.py#L119-L124) (in that case ExtractReview plug-in in the publish UI should show that log).

Could you confirm that e.g. Extract Thumbnail does not show in the publishing UI when using existing frames? And could you check those other logs I mentioned?

I think the root of the issue will be there.

**Comment by BigRoy** [comment]
@maxpareschi I believe you mentioned this issue again today saying that you are still facing it. Looking back at my last message above could you maybe further identify the issue on your end?
