### ISSUE TITLE
Deadline: checking existing frames fails when there is number in file name

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#3829]
## Problem

`validate_sequence_frames` fails when there is number in file name (other then frame number). It breaks `clique` asembly.

[cuID:2uxa4yb]

**Comment by BigRoy** [comment]
Is that the same as this PR? https://github.com/pypeclub/OpenPype/pull/3683

Issue is likely introduced with this PR: https://github.com/pypeclub/OpenPype/pull/3611 - since then it considers more of the filename for frame numbering since `clique.PATTERNS["frames"]` would have avoided that BUT would've required a dot before the frames.

**Comment by BigRoy** [comment]
We're likely better off defining our own patterns like the `frames` on that still expect the frames in that specific location (at end of file, before extension but don't require the dot.)

So it could be `.*([0-9]+)\.{ext}$`. Might be even better if we could pass the explicit extension to the assemble command or patterns so that we could also correctly detect extensions that might require double dots like `.ass.gz`.

Once we've found out the assembling/pattern matching that does what we want - then we should just provide it as a utility function in OpenPype so we can rely on that single entry to files collection. `clique.assemble` by default has shown it doesn't do what we wanted it to do - it leaves too much up to chance.

**Comment by antirotor** [comment]
Yep, I agree that using that specific regex with provided extension will solve most of these issues. I haven't yet identified all the places we are doing this but my guess is that in most (if not all) of them we already know the extension to be used.

**Comment by kalisp** [comment]
General plugin got removed a while ago, for Unreal it gets fixed by https://github.com/ynput/OpenPype/pull/5533

Standardization of `clique.assembly` should be implemented instead of this issue, see https://github.com/ynput/OpenPype/issues/4361
