### ISSUE TITLE
Maya: Look Manager Get All Assets on Layout not working

### ISSUE THREAD

**Issue by Jeremyball** [ynput/OpenPype#4044]
**Running version**
3.14.5

**Describe the bug**
In Maya's Look Manager, **Get All Assets** doesn't work on a referenced layout. Also when you click out of the gui, it disappears behind Maya's window.

**To Reproduce**
1. New Scene
2. Launch **Loader** 
3. Right click on Layout, select reference
4. Launch Look Manager, click on  **Get All Assets**
5. Nothing happens
6. In outliner, select the top group of the layout reference ( Look Manager disappears behind Maya) 
7. Alt tab to get look manager back
8. **Get Assets From Selection** lists assets

**Expected behavior**
Click **Get All Assets** and it lists all the assets. Window should stay in front of Maya.

Clicking **Get All Assets**:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/54645515/198855942-4e7c0904-6957-4fef-8a58-f10f4a2df27c.png">

Select top group:
<img width="391" alt="image" src="https://user-images.githubusercontent.com/54645515/198855966-677307d6-d12b-42d8-909a-dcb1efed1030.png">

Clicking  **Get Assets From Selection**:
<img width="301" alt="image" src="https://user-images.githubusercontent.com/54645515/198855895-d2dbae93-1dfc-465a-af81-bf9e20cb7364.png">

**Desktop:**
 - OS: Windows 11
 - Host: Maya 2023

[cuID:OP-4330]

**Comment by m-u-r-p-h-y** [comment]
is it connected to issue we have with layout publishing? #4030

**Comment by BigRoy** [comment]
This is likely due to how [Get all assets](https://github.com/pypeclub/OpenPype/blob/0d38c76f5402cd99e5a70385667ff1a5f0885eb7/openpype/tools/mayalookassigner/commands.py#L77-L97) works. Admittedly it's a confusing implementation for users and should just be changed [here](https://github.com/pypeclub/OpenPype/blob/bf3b9407cb8c8b05abde6a2df2145b4f86198a07/openpype/tools/mayalookassigner/widgets.py#L97-L98) to:

```python
nodes = cmds.ls(dag=True, noIntermediate=True, long=True)
items = commands.create_items_from_nodes(nodes)
```

And you're good to go.
