### ISSUE TITLE
Maya: Frame range validator gets error during publish of animation when shot range was changed and differ

### ISSUE THREAD

**Issue by LiborBatek** [ynput/OpenPype#4141]
When user changes orig frame range for particular shot in database these changes arent reflected on animation family/rig in its frame ranges params. Its not exposed to user by default and repair action wont help (can happen even when user has new and correct frame range set so there is no obvious reason for validating error but it differ on actual animation/rig asset.

for example original shot ```frame range``` ```1-25``` changed in DB to ```1001-1100``` and correctly set in maya too (seen on maya timeline) still get error during publish/validation.
![image](https://user-images.githubusercontent.com/112623825/203991581-88a022a9-235f-42a2-aa72-f4ffc979d1ee.png)

caused by animation/rig asset loaded in old frame range dont get updated and trigger error
![image](https://user-images.githubusercontent.com/112623825/203991764-1f2f651a-bcbf-4965-a04b-d30eab4ec83e.png)

when manually changed by user to proper frame range ```1001-1100``` all works as expected.

OP should give warning and Repair action should work on actual anim/rig asset and set it correctly. However there can be user cases when different frame ranges needed.

For example for extra loong shot lets say 5000 frames, user would like to publish shorter animation cache just for particular frames not full range because of short appearence of the asset in the shot (like 100 frames only) so repair/validating should be optional but not mandatory. Also there could be obvious cases when warning/repair action should always happen like anim/rig asset frame range out of the new one for ie

asset being ```1-25```
shot being ```1001-1100```

obviously not on purpose because doesnt fit to the shot range at all shoud be allways treated by repair action.

And vice versa

asset being ```1070-1099```
shot being ```1001-1100``` 
should be ok  and done on purpose so its users decision to make wether trigger repair action/validator for it or not ...fitting the shot range not exceed it 

 

[cuID:[OP-4514](https://app.clickup.com/t/34g36c2)]

**Comment by BigRoy** [comment]
As far as I can tell this 'invalidating' currently is the expected behavior of Validate Frame Range. By default it validates where an instance is set to exactly match the asset's 'frame range' with the current settings.

- If the user wants to deviate from that frame range explicitly they can disable the validator to explicitly say _"I'm ok with having a different frame range"_.
- If the shots frame range was changed for the shot in the database then the user will indeed get a validation error for their existing scene - the "repair frame range" will repair the frame range of the instance. Note that repair frame range on the instances does not do any changes whatsoever to the scene's frame range itself. That is the expected behavior.

Is still issue still valid to remain open?

**Comment by BigRoy** [comment]
@LiborBatek Are you referring to this issue https://github.com/ynput/OpenPype/issues/4272 ?

If so, can you check out PR #4279 whether that solves the issues you were having with it?

**Comment by LiborBatek** [comment]
@BigRoy no, this PR is about something different, however those two #4272 and #4279 can be connected...will test it if the issue are solved by it. thx

**Comment by BigRoy** [comment]
@LiborBatek was this solved since?

**Comment by LiborBatek** [comment]
@BigRoy tested in latest develop and all works fine. I guess this PR can be closed...
