### ISSUE TITLE
Maya: focalLength should be collected also for render families

### ISSUE THREAD

**Issue by kalisp** [ynput/OpenPype#4789]
**Running version**
[ex. 3.15.3-nightly.2]

**Describe the bug**
`{focalLenght}` was added into burnin profiles, but currently is only collected in `collect_review.py`. Problem is that `render` family uses burnin profiles too. (At least noticed in Maya when rendering multiple render passes.)

**To Reproduce**
1. Create multiple render passes in Maya
2. Render on Farm
3. It will fail with:.
[focal_length_fail.txt](https://github.com/ynput/OpenPype/files/11160488/focal_length_fail.txt)

**Expected behavior**
Render family shouldn't fail

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Host: noticed in Maya, but would probably affect all hosts with 'render' family

[cuID:[OP-5551](https://app.clickup.com/t/861mmd6ex)]

**Comment by tokejepsen** [comment]
> @tokejepsen what do you think?

Yeah lets try and isolate it to playblasts/reviews only. If a studio wants focal length support for renders then we can implement it properly (somehow).

**Comment by BigRoy** [comment]
So the original production breaking bug has been resolved. However this issue is a decent remainder that at some point we might want to include the information for renders too, but I wouldn't say it's high priority.

Note also that I believe both Arnold and Redshift (as an example) write the focal length in the metadata of the output images. (Right?)

**Comment by antirotor** [comment]
I am closing this, but it might still be an issue for additional hosts like Unreal. In that case, lets create host-specific issue.
