### ISSUE TITLE
enhancement: Houdini: Unable to duplicate ROP node to duplicate a publish instance

### ISSUE THREAD

**Issue by BigRoy** [ynput/OpenPype#4820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Please state which of feature you have in mind and describe what are its shortcomings?

It's currently hard to duplicate an existing publish instance (ROP node) to allow quickly duplicating the behavior and create a new instance natively to houdini. 

This is due to the node storing the `instance_node` value and the `instance_id` which means that the duplicated instance would not show in the Publisher UI (due to same `instance_id`), once you change the `instance_id` the `instance_node` fails due to the duplicated node not having the same path.

**Warning:** The `instance_node` value being stored on the node also means it breaks publishing whenever an artist would change the node name but not the attribute.

### How would you imagine the enhancement of the feature?

1. Upon a conflict of `instance_id` it should be able to differentiate the two and maybe generate a new id for one of the two?
2. `instance_node` should **never** be stored on the node since that value is the node's path in the workfile. That should **always** be based on the node's actual path (thus parent + name, `node.path()`).

### Is there any more labels you wish to add?

- [X] I have searched labels and added any

[cuID:[OP-5573](https://app.clickup.com/t/861mmp5j1)]

**Comment by BigRoy** [comment]
I think this is actually an **issue globally to the new publisher**. The same issue also exists in **Fusion**. When duplicating a saver you get the same issue described for Houdini. After duplicating you'll still only see _one of the two_ savers in the publisher but from that moment onwards you don't really know which of the two savers it is actually processing.

**Comment by mkolar** [comment]
@BigRoy do you think this is still issue with the latest changes to the publisher?

**Comment by BigRoy** [comment]
Did a quick test in latest develop. Issue still exists. Duplicating an instance ROP node will fail to show the instance twice.

![image](https://github.com/ynput/OpenPype/assets/2439881/2804fac5-4312-4818-a77d-591c8154bdf3)

**Comment by mustafa-zarkash** [comment]
I managed to create new instances by duplicate the ROP node 
I made these few changes:

- add `subset_identifier` node (because it always has a fixed value)
- `subset` is derived from `subset_identifier` and node name 
    > which eliminate subset name repetition
- `instance_node` : `opfullpath(".")`
- `instance_id` : generate new `uuid4`
    > I achieved it using a button (as a prototype)
    
let me know what do you think. 
@BigRoy @mkolar  
    
https://github.com/ynput/OpenPype/assets/20871534/49817a09-87e1-4464-8c4d-8c72587970c6

**Comment by mustafa-zarkash** [comment]
@BigRoy 

A little update, I was playing around with created instances.
 I noticed that some parameters can be dynamic such that: 

- variant = node name
- subset = family + variant
- instance_node = expression that returns node path  

Publisher seemed to be fine with that!  
It forbids having multiple instances with the same subset name
it's a starting point to allow creating new instances by duplicating existent instances. 

<table>
  <tr>
    <th>Original</th>
    <th>Updated</th>
 </tr>
 <tr>
    <th><img src="https://github.com/ynput/OpenPype/assets/20871534/c0251871-969a-4fcb-b58d-9c087bc19798"></th>
    <th><img src="https://github.com/ynput/OpenPype/assets/20871534/f53fe4a0-2b96-454c-85bb-14677ce358c3"></th>
 </tr>
 <tr>
    <th>

DEBUG: Instance Name: Sphere

Instance Data{
'family': 'pointcache',
'name': 'pointcacheSphere',
'subset': 'pointcacheSphere',
'asset': 'lamp',
'task': 'Modeling',
'label': 'pointcacheSphere',
'families': ['abc'],
'representations': [],
'thumbnailSource': None,
'id': 'pyblish.avalon.instance',
'active': 1,
'creator_identifier': 'io.openpype.creators.houdini.pointcache',
'variant': 'Sphere',
'folder01': 2,
'stdswitcher51': 0,
'tprerender': 1,
'prerender': '',
'lprerender': 'hscript',
'tpreframe': 1,
'preframe': '',
'lpreframe': 'hscript',
'tpostframe': 1,
'postframe': '',
'lpostframe': 'hscript',
'tpostrender': 1,
'postrender': '',
'lpostrender': 'hscript',
'instance_node':'/out/pointcacheSphere',
'instance_id': '39e92728-783c-46a6-ab36-0f6fb49931be',
'creator_attributes': {},
'publish_attributes': {},
'transientData': {},
'output_node': <hou.SopNode of type output at /obj/sphere/output0>
}
</th>
<th>

DEBUG: Instance Name: Cube

Instance Data{
'family': 'pointcache',
'name': 'pointcacheCube',
'subset': 'pointcacheCube',
'asset': 'lamp',
'task': 'Modeling',
'label': 'pointcacheCube',
'families': ['abc'],
'representations': [],
'thumbnailSource': None,
'id': 'pyblish.avalon.instance',
'active': 1,
'creator_identifier': 'io.openpype.creators.houdini.pointcache',
'variant': 'Cube',
'folder01': 2,
'stdswitcher51': 0,
'tprerender': 1,
'prerender': '',
'lprerender': 'hscript',
'tpreframe': 1,
'preframe': '',
'lpreframe': 'hscript',
'tpostframe': 1,
'postframe': '',
'lpostframe': 'hscript',
'tpostrender': 1,
'postrender': '',
'lpostrender': 'hscript',
'instance_node': '/out/Cube',
'instance_id': 'f27524d8-5e31-423a-b651-93a84db8ecca',
'creator_attributes': {},
'publish_attributes': {},
'transientData': {},
'output_node': <hou.SopNode of type output at /obj/cube/output0>
}
</th>
</tr>
</table>


Generating new instance_id is the missing step to completely allow creating new instance by duplicating existent instances. 
for testing I could achieve that by adding a button because it's intuitive to ask users to keep pushing that button!
```python 
from uuid import uuid4; hou.node(".").parm("instance_id").set(str(uuid4()))
```
![image](https://github.com/ynput/OpenPype/assets/20871534/6a7b0fa4-792d-4729-a1f4-3f6fbda81d26)

---
## Note
I tried applying these modifications in Houdini Creator
It was not as easy as it seems because everything is interconnected

**Comment by BigRoy** [comment]
Just proposed a solution here: https://github.com/ynput/OpenPype/pull/5490
