### ISSUE TITLE
Houdini: OCIO support

### ISSUE THREAD

**Issue by antirotor** [ynput/OpenPype#4836]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

We need to enhance OCIO support of AYON inside Houdini. With #4700 OCIO is correctly passed to Houdini, but setting OCIO profiles (and other options) on relevant nodes needs to be done manually. Like these options in OpenGL ROP (introduced by #3839):

![image](https://user-images.githubusercontent.com/33513211/231497164-59721e27-48b9-489f-b41f-36da3a08ee4d.png)

This is somehow similar to #4833.

There might be other places to set.

### How would you imagine the implementation of the feature?

It should be done as it is already done in Nuke, where you can set color spaces like this:

![image](https://user-images.githubusercontent.com/33513211/231499570-e81aef2f-003a-4b59-b3c4-ed3c7c514912.png)

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[OP-5602](https://app.clickup.com/t/861mn7n0c)]

**Comment by BigRoy** [comment]
What would be a decent default colorspace to set for the review output files. What setting should we obey to?
Would it the preferred rendering space? or the display space? (Houdini doesn't have any settings for that however).

**Comment by mustafa-zarkash** [comment]
I was reviewing this issue [#4833](https://github.com/ynput/OpenPype/issues/4833) 
and I believe it depends on this issue. 

As far as I know, Houdini requires setting OCIO profiles (and other options) manually as Houdini nodes don't inherit color management settings like in Maya. 

I can think of two solutions 
1. Set color space dynamically so that a plugin will deduce what color space to use from default display and default view
2. Expose Parameters to Ayon/OpenPype Settings UI so that aplugin will use these exposed parameters

For the mentioned example `OpenGL` 
I used the same OCIO Color correction as `hou.Color.ocio_defaultView()` which is alsmost the same that happens with Maya playblast (_to use view transform_)

![image](https://github.com/ynput/OpenPype/assets/20871534/d44eca3e-cc57-4822-ad59-67dd38819844)

There's also another problem in houdini that not all nodes have explicit colorspace parameters, and they will use `scene_linear` implicitly (e.g. mantra, texture read). 
so, I think there will be some tweaking in all ROPs. 

what do you think ? 
@BigRoy @antirotor @moonyuet

**Comment by antirotor** [comment]
I am not sure if we should touch explicit set colorspaces. My guess is that productions usually assume that colorspaces that are explicitly set remains so, but I don't know. Maybe we should implement is  when requested and it could be done as in Nuke perhaps? Otherwise the way with `ocio_defaultView()` seems reasonable for me.

**Comment by BigRoy** [comment]
This overlaps a lot with https://github.com/ynput/OpenPype/issues/67

@MustafaJafar still relevant?

**Comment by MustafaJafar** [comment]
> This overlaps a lot with https://github.com/ynput/OpenPype/issues/67
yes, they are, as far as I know.

The associated internal ticket was closed by ondrej so it's fair to close this one.

For reference, it's related to
https://github.com/ynput/OpenPype/pull/5322
https://github.com/ynput/ayon-core/pull/36
