### ISSUE TITLE
Bug: Substance Painter not starting when Global Color Management System Enabled

### ISSUE THREAD

**Issue by LiborBatek** [ynput/OpenPype#5241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

When launching Substance Painter via Launcher it wont start due to global ColorManagement On.

![image](https://github.com/ynput/OpenPype/assets/112623825/7c17d9f2-4347-4861-b8f0-41fd0b57f517)

### Expected Behavior:

Should start normally even when global CMS being set ON.

### Version

3.15.12-nightly.2

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. Turn on Global Color management system in OP Project Settings/ Global
2. Launch Substance painter via OP Launcher 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

[cuID:[OP-6323](https://app.clickup.com/t/861n10pyb)]

**Comment by moonyuet** [comment]
I am not sure the pre-ocio-hook would work for SP, but it is probably the reason why SP not starting as expected.
The way how the colorspace setting of substance painter works is a bit different from other dccs(and even Substance Designer). In other hosts like Maya or Houdini, you can set up the colorspace config o. But painter doesn't allow to do this. SP needs the user to set up the colorspace config while you are creating new spp project. (Take the screenshot below as references)

![image](https://github.com/ynput/OpenPype/assets/64118225/f1a9e0bf-b006-42a2-a8a6-8a1006bac92b)

But when you have existing spp project, you can edit the colorspace config through "Edit->Project Configuration". And you can't click Project Configuration unless you have loaded spp project.
Instead of setting up color config when starting new scene with pre-ocio-hook, I think it's better idea to add the action into the menu which allows to set up the correct ocio config, or setting up the correct ocio config when opening last workfile.

**Comment by BigRoy** [comment]
The error seems to be related to likely the Substance Painter settings schema not being set up correctly - I'll take a look.
The `OCIO` env var works fine for Substance Painter by the way.
