### ISSUE TITLE
Houdini: Hard coded "start_frame" raises error in validations

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior:

Hard coded "frameStart" value in several houdini plugins 
```python
frame = instance.data.get("frameStart", 0)
```
It causes an error when imported asset doesn't have a 0000 frame. 

> [!NOTE]
> This only happens during validation (alembic, fbx static mesh, vdb)
> when the associated ROP trange is set to render current frame 
> one solution is to make a validator that 
> - changes `render current frame` to `render frame range`
> - set `f1` and `f2` of the ROP to the current frame value.

![image](https://github.com/ynput/OpenPype/assets/20871534/e6926425-24cb-4f43-b186-afd8913f8f70)

### Expected Behavior:

Validators should validate what the user see in the view port whether the current frame or the start frame of the current frame range. 
Depending on the situation: 

### Version

3.16.4

### What platform you are running OpenPype on?

Windows

### Steps To Reproduce:

1. import an asset that doesn't exists at frame 0 (e.g. a BEGO cache that doesn't have 0000 frame) 
2. publish

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the bug report.

### Additional context:
Suggested Solution
```python
        # Get frame
        frame = hou.intFrame()
        trange = rop_node.parm("trange").eval()
        if trange:
            frame = int(hou.playbar.frameRange()[0])

        frame = instance.data.get("frameStart", frame)

        # Get Geo at that frame
        geo = output_node.geometryAtFrame(frame)
        if not geo:
            cls.log.warning("No geometry found,"
                            " skipping check..")
            return
```
Validators associated with this issue

https://github.com/ynput/OpenPype/blob/4b00d2a9b96f0e877baae03371e4d8fd785ded05/openpype/hosts/houdini/plugins/publish/validate_abc_primitive_to_detail.py#L76-L86

https://github.com/ynput/OpenPype/blob/4b00d2a9b96f0e877baae03371e4d8fd785ded05/openpype/hosts/houdini/plugins/publish/validate_alembic_input_node.py#L53

https://github.com/ynput/OpenPype/blob/4b00d2a9b96f0e877baae03371e4d8fd785ded05/openpype/hosts/houdini/plugins/publish/validate_primitive_hierarchy_paths.py#L83

https://github.com/ynput/OpenPype/blob/4b00d2a9b96f0e877baae03371e4d8fd785ded05/openpype/hosts/houdini/plugins/publish/validate_vdb_output_node.py#L118

[cuID:[OP-6727](https://app.clickup.com/t/861najumv)]

**Comment by BigRoy** [comment]
I agree that it shouldn't fallback to frame zero. However - I'd also argue that most of these validators run over instances that are supposed to have `frameStart` data. Even if it were a single frame it should be `frameStart` and `frameEnd` containing the single frame. 

So I'd argue that _actually_ most of these should be `instance.data["frameStart"]` since that data should be present and it is isn't then **that** is the bug.

For the cases where we expect instance to not have a frameStart data then I think current frame makes sense from an artist's perspective but not so much from a pipeline perspective because the behavior then turns very different if the user just happens to be on another frame currently making it unpredictable. As such, from a development perspective I think using the  start frame might make more sense - but then again, for those cases it might make just as much sense to ensure the instance actually as the frameStart data we're expecting anyway.

Can you think of an instance currently that should NOT have `frameStart` data that does get validated by any of these validators?

**Comment by mustafa-zarkash** [comment]
Re-thinking of this problem. 

When ever this line is used, "frameStart" should always exists  and it will never fallback to frame zero.
```python
 frame = instance.data.get("frameStart", 0) 
``` 

However I found out two things 
1. if trange value == 0 
Then it should be: 
```python
data["frameStart"] =  hou.intFrame()
data["frameEnd"] =  hou.intFrame()
```
https://github.com/ynput/OpenPype/blob/594bf8a1f66c8a22112fbb2748b1082db89f2df8/openpype/hosts/houdini/plugins/publish/collect_instance_frame_data.py#L46-L50

2.  when setting start and end frame from Opnepype dropdown menu
when start == end, houdini use (start  and end+1) 
although I can set start and end to the same number from 
![image](https://github.com/ynput/OpenPype/assets/20871534/9eb2e443-3701-4e33-95e2-8501275b816e)


--- 
> Can you think of an instance currently that should NOT have frameStart data that does get validated by any of these validators?

I think my suggested solution will not be required after applying the above fixes 
but to ask your question : 
it will only happen when artist render the current frame 
*FYI, it generates a bug with bgeo! *
![image](https://github.com/ynput/OpenPype/assets/20871534/8b0fa1f3-c7b5-4090-b1d8-81caadaa375d)

**Comment by mustafa-zarkash** [comment]
I think this should be enough! 
```python
frame = instance.data.get("frameStart", hou.intFrame())
```

**Comment by mustafa-zarkash** [comment]
> That's why I believe initially we never allowed Render Current Frame as an option for the ROP nodes pre-OpenPype (not sure if it's allowed now actually)

As far as I know, No validator for that at the moment.
