### ISSUE TITLE
Enhancement: Products linked by version

### ISSUE THREAD

**Issue by MustafaJafar** [ynput/OpenPype#5894]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Please describe the feature you have in mind and explain what the current shortcomings are?

I came across a [question on community](https://community.ynput.io/t/replicating-shotgrid-pipeline-concepts-in-ayon/724) and I've a thought: 
question: 
```
Products linked by version, e.g. review v04 belongs to model v03 both belong to workfile v05
```
Milan's answer: 
```
By design they are independent.
In Nuke, we added a built in mechanism to sync versions of products to workfile version. 
```
my question: 
would it be beneficial if artists are able to add relations to products ? 
e.g. this screenshot. 
![image](https://github.com/ynput/OpenPype/assets/20871534/46886c77-196b-4b68-89ac-05d76746b679)

### How would you imagine the implementation of the feature?

I think of many ways

1. A checkbox in publisher that considers all published products are related to each other 
2. A tool that edits meta data to add this piece of data manually

Note that: 
This piece of data may mean nothing to ayon but provides users with some information. 

### Are there any labels you wish to add?

- [X] I have added the relevant labels to the enhancement request.

[cuID:[OP-7394](https://app.clickup.com/t/86bwdz27b)]

**Comment by BigRoy** [comment]
> In Nuke, we added a built in mechanism to sync versions of products to workfile version. 

This actually exists across different hosts via `project_settings/global/publish/CollectAnatomyInstanceData/follow_workfile_version`:

![follow_workfile_version](https://github.com/ynput/OpenPype/assets/2439881/5f72737e-28e1-4954-a38f-d8f6d4c21016)

---

Conceptually I don't really see how this "linking" is very special nor do I see how it would be different to what tooling like the **[AYON Node Graph](https://ynput.io/ayon/addons/node-graph/)** would allow, because as I understood it'd allow you to design any linking between anything and thus also be able to do "Product version -> Product version" linking similar to how Input Dependencies are tracked, etc.

> 1. A checkbox in publisher that considers all published products are related to each other

Actually, as a first step I feel like during the publish we should be ingesting per version along what the "publish session id" is and store that as metadata. Even if the versions are not "linked" for now then we'll have the metadata available of which things were published together.

**collect_publish_session_id.py**
```python
import pyblish.api
import uuid

def CollectSessionId(pyblish.api.ContextPlugin):
    order = pyblish.api.CollectorOrder - 0.499
    def process(self, context):
        context.data["publishSessionId"] = str(uuid.uuid4())
```

```python
# And in the integrator put that session id into the version data
version["data"]["publishSessionId"] = context.data["publishSessionId"]
```
_Likely also needs to be in hero version integrator?_

By solely doing that we would then be able to detect which versions were published together. - which could made into 'links' later as well.

But it also allows a studio to for example on each publish write out the Publish Report JSON to a database and then if they wanted to debug how a particular version was made they can use the `publishSessionId` to load that into the Publish Report Viewer to see exactly what occurred during that publish in the publisher. 👍 Which could make for a useful debugging workflow from e.g. a `DebugAddon`.

> 2. A tool that edits meta data to add this piece of data manually

[AYON Node Graph](https://ynput.io/ayon/addons/node-graph/)?

**Comment by BigRoy** [comment]
Also note that it should be the case that on each publish each version gets a Dependency input to the published workfile - as such, to find all other publishes from that particular workfile publish you can check its Dependency outputs.

What I still wanted to be able to do is to in the "Dependency" tab to in the Loader to be able to double click an entry to make the UI 'go there' so that one could then e.g. double click on the "Workfile" input dependency and from there directly see all the outputs. Bonus points for then being able to select all output dependencies in that tab, press enter and make the UI go into a multiselection for the "valid assets" (in most cases it'll be one asset if you don't publish to multiple assets) and select all the version/representations as well so that one could e.g. load them all at once if needed.

**Comment by mkolar** [comment]
I feel that @BigRoy has answered really well and considering this is a lot more robust in AYON, I'd close this. Better question for a forum btw.
